#!/usr/bin/env python3
# Inyecta data-pt (PT-BR) junto a cada data-es, y data-pt-ph junto a data-es-ph.
import glob, re

TR = {
 "&ldquo;Ahora entregamos informes el mismo día. El tiempo de redacción bajó tanto que nuestros radiólogos duplicaron su producción sin trabajar más horas.&rdquo;":"&ldquo;Agora entregamos os laudos no mesmo dia. O tempo de redação caiu tanto que nossos radiologistas dobraram a produção sem trabalhar mais horas.&rdquo;",
 "&ldquo;Con el software de IA nuestros radiólogos informan en una fracción del tiempo y entregamos resultados el mismo día.&rdquo;":"&ldquo;Com o software de IA nossos radiologistas laudam em uma fração do tempo e entregamos resultados no mesmo dia.&rdquo;",
 "&ldquo;Por primera vez vemos la producción y el costo real de cada equipo en un solo lugar. La distribución de turnos ahora la decide el dato, no la intuición.&rdquo;":"&ldquo;Pela primeira vez vemos a produção e o custo real de cada equipamento em um só lugar. A distribuição de turnos agora é decidida pelo dado, não pela intuição.&rdquo;",
 "&ldquo;Recuperaron una bobina que dábamos por perdida. Nos evitaron el downtime y el costo de una pieza nueva.&rdquo;":"&ldquo;Recuperaram uma bobina que dávamos como perdida. Evitaram o downtime e o custo de uma peça nova.&rdquo;",
 "&ldquo;Reducir hasta un 75% la dosis en PET-CT cambió cómo planificamos los estudios. Mejores imágenes, más seguras para el paciente y adquisiciones más rápidas.&rdquo;":"&ldquo;Reduzir até 75% a dose em PET-CT mudou como planejamos os estudos. Melhores imagens, mais seguras para o paciente e aquisições mais rápidas.&rdquo;",
 "&ldquo;Somos una empresa de prestación de servicios y comercialización de tecnologías médicas enfocada en el área del diagnóstico por imágenes, conformada por un equipo multidisciplinario en ingeniería técnica, comercial y administrativa.&rdquo;":"&ldquo;Somos uma empresa de prestação de serviços e comercialização de tecnologias médicas focada na área de diagnóstico por imagem, formada por uma equipe multidisciplinar em engenharia técnica, comercial e administrativa.&rdquo;",
 "&ldquo;Soporte multimarca que de verdad responde. El uptime de nuestro resonador mejoró notablemente este año.&rdquo;":"&ldquo;Suporte multimarca que realmente responde. O uptime do nosso ressonador melhorou bastante neste ano.&rdquo;",
 "Adaptado a tu rol y a tu centro":"Adaptado ao seu perfil e ao seu centro",
 "Adoptalas juntas como plataforma integral, o de a una. Todas autorizadas por FDA, todas multimarca, todas conectadas a tu PACS/RIS.":"Adote-as juntas como plataforma integral, ou uma a uma. Todas com autorização FDA, todas multimarca, todas conectadas ao seu PACS/RIS.",
 "Agendá un demo personalizado y te mostramos el impacto sobre tu producción, tus tiempos de entrega y la dosis — con tus equipos y tu flujo de trabajo.":"Agende uma demo personalizada e mostramos o impacto na sua produção, nos seus prazos de entrega e na dose — com os seus equipamentos e o seu fluxo de trabalho.",
 "Al enviar aceptás ser contactado por el equipo de Nexolibre. Nunca compartimos tus datos.":"Ao enviar, você aceita ser contatado pela equipe da Nexolibre. Nunca compartilhamos os seus dados.",
 "Argentina":"Argentina",
 "Argentina — soporte, laboratorio y proyectos":"Argentina — suporte, laboratório e projetos",
 "Autorizado por FDA":"Autorizado pela FDA",
 "Aún no sé":"Ainda não sei",
 "Bobinas":"Bobinas",
 "Bobinas MRI, módulos de RF y gradientes — restaurados, testeados y listos para instalar.":"Bobinas MRI, módulos de RF e gradientes — restaurados, testados e prontos para instalar.",
 "Bobinas y módulos RF / gradientes":"Bobinas e módulos RF / gradientes",
 "Bobinas, gradientes, RF, fuentes e inyectores — recuperados y testeados. Buscá por marca, modelo de equipo o número de parte. El stock se actualiza permanentemente.":"Bobinas, gradientes, RF, fontes e injetores — recuperados e testados. Busque por marca, modelo de equipamento ou número de peça. O estoque é atualizado permanentemente.",
 "Buscá por marca, modelo de equipo o número de parte. Cada pieza es recuperada y testeada en nuestros laboratorios.":"Busque por marca, modelo de equipamento ou número de peça. Cada peça é recuperada e testada em nossos laboratórios.",
 "Cada herramienta que representamos cuenta con autorización FDA — software de grado clínico en el que podés confiar.":"Cada ferramenta que representamos possui autorização FDA — software de grau clínico em que você pode confiar.",
 "Cada laboratorio de Nexolibre tiene sus propias especialidades y capacidades. Explorá lo que ofrecemos en Argentina, Chile y USA.":"Cada laboratório da Nexolibre tem suas próprias especialidades e capacidades. Explore o que oferecemos na Argentina, no Chile e nos EUA.",
 "Cada laboratorio, sus especialidades":"Cada laboratório, suas especialidades",
 "Catálogo de partes":"Catálogo de peças",
 "Centro de Diagnóstico por Imágenes":"Centro de Diagnóstico por Imagem",
 "Centro de diagnóstico por imágenes":"Centro de diagnóstico por imagem",
 "Chile":"Chile",
 "Chile — soporte MRI/CT y laboratorio de electrónica":"Chile — suporte MRI/CT e laboratório de eletrônica",
 "Clínica privada":"Clínica privada",
 "Confianza":"Confiança",
 "Conocer Gauss Connect":"Conhecer o Gauss Connect",
 "Conocer RadDictate y SubtleIA":"Conhecer o RadDictate e o SubtleIA",
 "Conocer software →":"Conhecer o software →",
 "Conocé el software IA →":"Conheça o software de IA →",
 "Conocé la empresa →":"Conheça a empresa →",
 "Conservá tu visualizador actual: la IA de dictado puede implementarse sobre tu plataforma existente (sujeto a evaluación)":"Mantenha o seu visualizador atual: a IA de ditado pode ser implementada sobre a sua plataforma existente (sujeito a avaliação)",
 "Conservá tu visualizador actual: la IA de transcripción puede implementarse sobre tu plataforma existente (sujeto a evaluación)":"Mantenha o seu visualizador atual: a IA de transcrição pode ser implementada sobre a sua plataforma existente (sujeito a avaliação)",
 "Consultar":"Consultar",
 "Consultar disponibilidad":"Consultar disponibilidade",
 "Contactanos":"Fale conosco",
 "Contacto":"Contato",
 "Contanos qué necesita tu equipamiento":"Conte o que o seu equipamento precisa",
 "Contanos tu equipo y el problema — el laboratorio más cercano te responde.":"Conte o seu equipamento e o problema — o laboratório mais próximo responde.",
 "Control y previsión de producción: finanzas, eficiencia del personal y distribución de turnos":"Controle e previsão de produção: finanças, eficiência da equipe e distribuição de turnos",
 "Control y previsión de producción: finanzas, eficiencia del personal, distribución de turnos":"Controle e previsão de produção: finanças, eficiência da equipe, distribuição de turnos",
 "DICOM · PACS / RIS · Autorizado FDA":"DICOM · PACS / RIS · Autorizado FDA",
 "Del equipo al informe final. Software con IA, conectado a DICOM, PACS y RIS, que aumenta la producción, reduce los tiempos de entrega y mejora la calidad de imagen en MRI, CT y PET-CT.":"Do equipamento ao laudo final. Software com IA, conectado a DICOM, PACS e RIS, que aumenta a produção, reduz os prazos de entrega e melhora a qualidade de imagem em MRI, CT e PET-CT.",
 "Del monitoreo del equipo al informe final. Conectado a DICOM, PACS y RIS — aumentando la producción, reduciendo tiempos de entrega y bajando la dosis al paciente.":"Do monitoramento do equipamento ao laudo final. Conectado a DICOM, PACS e RIS — aumentando a produção, reduzindo prazos de entrega e diminuindo a dose ao paciente.",
 "Diagnóstico por imágenes especializado":"Diagnóstico por imagem especializado",
 "Dictá e informá en una fracción del tiempo. La IA de transcripción reduce un 70% el tiempo de redacción y la IA de imagen te da estudios más rápidos y nítidos — para entregar resultados antes.":"Dite e laude em uma fração do tempo. A IA de transcrição reduz em 70% o tempo de redação e a IA de imagem oferece estudos mais rápidos e nítidos — para entregar resultados antes.",
 "Director de clínica / hospital":"Diretor de clínica / hospital",
 "Diseñado por radiólogos, para radiólogos: hanging protocols inteligentes, 2D · MPR · 3D · VR y estudios de 1000+ cortes que cargan en menos de un segundo":"Desenvolvido por radiologistas, para radiologistas: hanging protocols inteligentes, 2D · MPR · 3D · VR e estudos de 1000+ cortes que carregam em menos de um segundo",
 "Dueño de centro de diagnóstico":"Dono de centro de diagnóstico",
 "Email de trabajo":"E-mail de trabalho",
 "Empresa":"Empresa",
 "Envianos el modelo y el número de pieza — te respondemos con disponibilidad y tiempos de entrega.":"Envie o modelo e o número da peça — respondemos com disponibilidade e prazos de entrega.",
 "Enviar consulta":"Enviar consulta",
 "Equipamiento / Proyectos":"Equipamentos / Projetos",
 "Equipamiento y proyectos MRI/CT":"Equipamentos e projetos MRI/CT",
 "Equipo local en AR · CL · CO · USA":"Equipe local em AR · CL · CO · USA",
 "Equipo local en la región":"Equipe local na região",
 "Equipo multidisciplinario":"Equipe multidisciplinar",
 "Equipo y soporte local en Argentina, Chile, Colombia y USA.":"Equipe e suporte local na Argentina, no Chile, na Colômbia e nos EUA.",
 "Equipos MRI / CT":"Equipamentos MRI / CT",
 "Equipos y piezas críticas, disponibles":"Equipamentos e peças críticas, disponíveis",
 "Equipos y repuestos":"Equipamentos e peças",
 "Escribinos":"Escreva para nós",
 "Estudios más rápidos y nítidos — con menor dosis":"Estudos mais rápidos e nítidos — com menor dose",
 "Estudios por mes (opcional)":"Estudos por mês (opcional)",
 "Explorá nuestro catálogo de partes":"Explore o nosso catálogo de peças",
 "FDA y cumplimiento":"FDA e conformidade",
 "Flujo end-to-end: abrís el estudio, dictás por voz y el informe estructurado se genera con las mediciones ya cargadas — sin cambiar de ventana":"Fluxo end-to-end: você abre o estudo, dita por voz e o laudo estruturado é gerado com as medições já carregadas — sem trocar de janela",
 "Foto: equipo / laboratorio":"Foto: equipe / laboratório",
 "Foto: laboratorio Argentina":"Foto: laboratório Argentina",
 "Foto: laboratorio Chile":"Foto: laboratório Chile",
 "Foto: laboratorio USA":"Foto: laboratório EUA",
 "Foto: piezas / stock":"Foto: peças / estoque",
 "Fuentes":"Fontes",
 "Fuentes de poder e inyectores":"Fontes de alimentação e injetores",
 "Fuentes de poder e inyectores recuperados en nuestros laboratorios, con calidad comprobada.":"Fontes de alimentação e injetores recuperados em nossos laboratórios, com qualidade comprovada.",
 "Funciona con cualquier marca de equipos. No necesitás reemplazar tus scanners ni tu parque instalado.":"Funciona com qualquer marca de equipamentos. Você não precisa trocar os seus scanners nem o seu parque instalado.",
 "Funciona sobre tus escáneres actuales — sin hardware nuevo — e integra con tu PACS/RIS":"Funciona sobre os seus scanners atuais — sem hardware novo — e integra com o seu PACS/RIS",
 "Gauss Connect, RadDictate y SubtleIA: monitoreo, dictado de informes con IA y mejora de imagen para MRI, CT y PET-CT.":"Gauss Connect, RadDictate e SubtleIA: monitoramento, ditado de laudos com IA e melhoria de imagem para MRI, CT e PET-CT.",
 "Gradientes":"Gradientes",
 "Hablemos de tu equipamiento":"Vamos falar do seu equipamento",
 "Hablá con el equipo":"Fale com a equipe",
 "Hasta 75% de reducción de dosis al paciente en PET-CT":"Até 75% de redução de dose ao paciente em PET-CT",
 "IA de deep learning, autorizada por FDA, que mejora la calidad de imagen y acelera los estudios sobre tus equipos actuales — sin cambiar hardware. Acelera la adquisición de MRI hasta un 80%, reduce el ruido en estudios PET de bajo conteo con cualquier radiotrazador y permite reducir hasta un 75% la dosis al paciente en PET-CT.":"IA de deep learning, autorizada pela FDA, que melhora a qualidade de imagem e acelera os estudos sobre os seus equipamentos atuais — sem trocar hardware. Acelera a aquisição de MRI em até 80%, reduz o ruído em estudos PET de baixa contagem com qualquer radiotraçador e permite reduzir até 75% a dose ao paciente em PET-CT.",
 "IA para MRI, CT y PET-CT":"IA para MRI, CT e PET-CT",
 "IA para el Diagnóstico por Imágenes":"IA para o Diagnóstico por Imagem",
 "IA para toda el área de diagnóstico por imágenes":"IA para toda a área de diagnóstico por imagem",
 "Informá con un 70% menos de tiempo de redacción":"Laude com 70% menos tempo de redação",
 "Ingeniería de soporte MRI":"Engenharia de suporte MRI",
 "Ingeniería de soporte MRI, nuestro laboratorio de reparaciones y proyectos integrales de equipamiento MRI/CT.":"Engenharia de suporte MRI, nosso laboratório de reparos e projetos integrais de equipamentos MRI/CT.",
 "Ingeniería multidisciplinaria, cerca de tu equipo":"Engenharia multidisciplinar, perto do seu equipamento",
 "Ingeniería médica multimarca":"Engenharia médica multimarca",
 "Ingeniería médica multimarca para diagnóstico por imágenes. Soporte, equipos, piezas y software con IA.":"Engenharia médica multimarca para diagnóstico por imagem. Suporte, equipamentos, peças e software com IA.",
 "Ingeniería técnica, comercial y administrativa trabajando en conjunto para que tus sistemas de MRI y CT duren más y funcionen mejor — en Argentina, Chile y USA, con laboratorios propios.":"Engenharia técnica, comercial e administrativa trabalhando em conjunto para que os seus sistemas de MRI e CT durem mais e funcionem melhor — na Argentina, no Chile e nos EUA, com laboratórios próprios.",
 "Ingeniería técnica, comercial y administrativa trabajando en conjunto para tu centro.":"Engenharia técnica, comercial e administrativa trabalhando em conjunto para o seu centro.",
 "Ingeniería y laboratorios, por país":"Engenharia e laboratórios, por país",
 "Ingeniería y reparación":"Engenharia e reparo",
 "Ingeniería, piezas, equipos y software con IA":"Engenharia, peças, equipamentos e software com IA",
 "Inicio":"Início",
 "Institución":"Instituição",
 "Integración PACS / RIS":"Integração PACS / RIS",
 "Inteligencia técnica y de producción para tus equipos":"Inteligência técnica e de produção para os seus equipamentos",
 "Inyectores":"Injetores",
 "Jefe técnico / biomédico":"Chefe técnico / biomédico",
 "La eligen los equipos de imágenes de la región":"Escolhida pelas equipes de imagem da região",
 "La plataforma":"A plataforma",
 "Laboratorio":"Laboratório",
 "Laboratorio / Reparación de piezas":"Laboratório / Reparo de peças",
 "Laboratorio de electrónica y biomedicina":"Laboratório de eletrônica e biomedicina",
 "Laboratorio de reparaciones":"Laboratório de reparos",
 "Laboratorios de electrónica y biomedicina con recuperación de piezas críticas y testeo comprobado.":"Laboratórios de eletrônica e biomedicina com recuperação de peças críticas e teste comprovado.",
 "Laboratorios propios":"Laboratórios próprios",
 "Lo que nos distingue":"O que nos diferencia",
 "MRI más rápido":"MRI mais rápido",
 "MRI · CT · Multimarca · AR · CL · USA":"MRI · CT · Multimarca · AR · CL · USA",
 "Mantenimiento predictivo: detecta anomalías y degradaciones antes de que se transformen en una falla o un quench costoso":"Manutenção preditiva: detecta anomalias e degradações antes que se transformem em uma falha ou um quench custoso",
 "Maximizamos la vida útil de tus <span class='hl'>sistemas de diagnóstico</span>":"Maximizamos a vida útil dos seus <span class='hl'>sistemas de diagnóstico</span>",
 "Mayor calidad de imagen con adopción clínica comprobada":"Maior qualidade de imagem com adoção clínica comprovada",
 "Me interesa":"Tenho interesse em",
 "Mejora de imagen con deep learning para MRI y CT que acorta los tiempos de adquisición y eleva la calidad de imagen. En PET-CT permite una reducción drástica de la dosis — protegiendo a tus pacientes sin resignar confianza diagnóstica.":"Melhoria de imagem com deep learning para MRI e CT que reduz os tempos de aquisição e eleva a qualidade de imagem. Em PET-CT permite uma redução drástica da dose — protegendo os seus pacientes sem abrir mão da confiança diagnóstica.",
 "Menor dosis, estudios más rápidos y mejor calidad de imagen.":"Menor dose, estudos mais rápidos e melhor qualidade de imagem.",
 "Menores tiempos de adquisición en MRI y CT = más pacientes por día":"Menores tempos de aquisição em MRI e CT = mais pacientes por dia",
 "Mensaje":"Mensagem",
 "Mensaje (opcional)":"Mensagem (opcional)",
 "Monitoreo técnico 24/7 en tiempo real: nivel de helio, cold head, criocompresor, presión del magneto y riesgo de quench":"Monitoramento técnico 24/7 em tempo real: nível de hélio, cold head, criocompressor, pressão do magneto e risco de quench",
 "Monitoreo y operaciones":"Monitoramento e operações",
 "Multimarca":"Multimarca",
 "Multimarca MRI / CT":"Multimarca MRI / CT",
 "Más estudios con el mismo equipamiento y visibilidad operativa total.":"Mais estudos com o mesmo equipamento e visibilidade operacional total.",
 "Más estudios y cero sorpresas: prevení downtime, prolongá la vida útil del equipo y protegé tus ingresos.":"Mais estudos e zero surpresas: previna downtime, prolongue a vida útil do equipamento e proteja a sua receita.",
 "Más informes por turno y entrega más rápida a los pacientes":"Mais laudos por turno e entrega mais rápida aos pacientes",
 "Médico radiólogo":"Médico radiologista",
 "Médico radiólogo informante":"Médico radiologista laudador",
 "Módulos de RF y gradientes":"Módulos de RF e gradientes",
 "Nombre y apellido":"Nome e sobrenome",
 "Nuestra empresa":"Nossa empresa",
 "Nuestras publicaciones de equipos y repuestos MRI/CT":"Nossos anúncios de equipamentos e peças MRI/CT",
 "Nuestro laboratorio en USA se especializa en restaurar bobinas MRI, módulos de RF y gradientes, fuentes de poder e inyectores.":"Nosso laboratório nos EUA é especializado em restaurar bobinas MRI, módulos de RF e gradientes, fontes de alimentação e injetores.",
 "Nuestro stock rota constantemente. Decinos el modelo y el número de parte y lo buscamos en nuestros laboratorios de AR, CL y USA.":"Nosso estoque gira constantemente. Diga o modelo e o número da peça e procuramos nos nossos laboratórios de AR, CL e EUA.",
 "Nuevo":"Novo",
 "Nuevo · Software con IA":"Novo · Software com IA",
 "Opción solo IA":"Opção só IA",
 "Operación en Argentina, Chile y USA, con laboratorio propio en USA.":"Operação na Argentina, no Chile e nos EUA, com laboratório próprio nos EUA.",
 "Otro":"Outro",
 "Para centros, clínicas y hospitales":"Para centros, clínicas e hospitais",
 "Para médicos radiólogos informantes":"Para médicos radiologistas laudadores",
 "Parte de Grupo Nexo":"Parte do Grupo Nexo",
 "País":"País",
 "Pedir Demo":"Pedir Demo",
 "Pensado para adoptarse con confianza":"Pensado para ser adotado com confiança",
 "Piezas recuperadas disponibles en nuestra tienda":"Peças recuperadas disponíveis na nossa loja",
 "Plantillas de informe customizables y exportación a Word/PDF con firma digital":"Modelos de laudo personalizáveis e exportação para Word/PDF com assinatura digital",
 "Por qué Nexolibre":"Por que a Nexolibre",
 "Por qué los centros eligen Nexolibre":"Por que os centros escolhem a Nexolibre",
 "Presencia regional":"Presença regional",
 "Presentes en marketplaces internacionales":"Presentes em marketplaces internacionais",
 "Privacy by design: procesamiento local e integración con DICOM, PACS/RIS y HIS":"Privacy by design: processamento local e integração com DICOM, PACS/RIS e HIS",
 "Producto de interés":"Produto de interesse",
 "Productos":"Produtos",
 "Productos y stock":"Produtos e estoque",
 "Quiénes somos":"Quem somos",
 "Qué hacemos":"O que fazemos",
 "Red de hospitales":"Rede de hospitais",
 "Relevo en tiempo real de datos técnicos de equipos en MRI y CT":"Coleta em tempo real de dados técnicos de equipamentos em MRI e CT",
 "Representación oficial en":"Representação oficial em",
 "Repuestos MRI/CT recuperados y testeados":"Peças MRI/CT recuperadas e testadas",
 "Restauración de bobinas MRI":"Restauração de bobinas MRI",
 "Rol":"Cargo",
 "Seleccioná un rango…":"Selecione uma faixa…",
 "Seleccioná…":"Selecione…",
 "Servicio de Medicina Nuclear":"Serviço de Medicina Nuclear",
 "Servicios":"Serviços",
 "Servicios por país →":"Serviços por país →",
 "Sin compromiso — primero ves el retorno":"Sem compromisso — primeiro você vê o retorno",
 "Sin hardware nuevo":"Sem hardware novo",
 "Software":"Software",
 "Software con IA":"Software com IA",
 "Software con IA para el diagnóstico por imágenes. Representación oficial en Latinoamérica y USA.":"Software com IA para o diagnóstico por imagem. Representação oficial na América Latina e nos EUA.",
 "Solicitar mi Demo":"Solicitar minha Demo",
 "Solicitar un Demo":"Solicitar uma Demo",
 "Soporte en resonancia y tomografía":"Suporte em ressonância e tomografia",
 "Soporte especializado en resonancia y tomografía y un laboratorio de electrónica y biomedicina.":"Suporte especializado em ressonância e tomografia e um laboratório de eletrônica e biomedicina.",
 "Soporte remoto integrado y un único tablero para todas tus sedes, equipos y marcas":"Suporte remoto integrado e um único painel para todas as suas unidades, equipamentos e marcas",
 "Soporte técnico":"Suporte técnico",
 "Soporte técnico multimarca y laboratorios propios que recuperan piezas críticas de MRI/CT — por país.":"Suporte técnico multimarca e laboratórios próprios que recuperam peças críticas de MRI/CT — por país.",
 "Soporte técnico y venta de equipos MRI/CT, laboratorios propios de reparación con recuperación de piezas críticas, y software con IA — todo para el área de diagnóstico por imágenes.":"Suporte técnico e venda de equipamentos MRI/CT, laboratórios próprios de reparo com recuperação de peças críticas, e software com IA — tudo para a área de diagnóstico por imagem.",
 "Soporte técnico, repuestos, equipos o software con IA — contanos qué necesitás y nuestro equipo te responde a la brevedad.":"Suporte técnico, peças, equipamentos ou software com IA — conte o que você precisa e nossa equipe responde em breve.",
 "Soporte técnico, repuestos, equipos o software con IA — nuestro equipo local en Argentina, Chile y USA te responde a la brevedad.":"Suporte técnico, peças, equipamentos ou software com IA — nossa equipe local na Argentina, no Chile e nos EUA responde em breve.",
 "Stock de repuestos":"Estoque de peças",
 "SubtleHD (CT) y SubtleSYNTH: TC ultranítida y contrastes sintéticos sin adquisición adicional":"SubtleHD (CT) e SubtleSYNTH: TC ultranítida e contrastes sintéticos sem aquisição adicional",
 "SubtleHD (MR): hasta 80% más rápida la adquisición de MRI, manteniendo la calidad diagnóstica":"SubtleHD (MR): aquisição de MRI até 80% mais rápida, mantendo a qualidade diagnóstica",
 "SubtleHD (PET): denoising de adquisiciones de bajo conteo con cualquier radiotrazador, sobre PET, PET-CT y PET-MR existentes — hasta 75% menos dosis al paciente":"SubtleHD (PET): denoising de aquisições de baixa contagem com qualquer radiotraçador, sobre PET, PET-CT e PET-MR existentes — até 75% menos dose ao paciente",
 "También nos encontrás en":"Você também nos encontra em",
 "Tecnología médica con ingeniería propia":"Tecnologia médica com engenharia própria",
 "Teléfono / WhatsApp":"Telefone / WhatsApp",
 "Todas las herramientas se conectan a DICOM e integran con tu PACS y RIS existentes.":"Todas as ferramentas se conectam a DICOM e integram com o seu PACS e RIS existentes.",
 "Todos / aún no sé":"Todos / ainda não sei",
 "Trabajamos sobre cualquier marca de equipos MRI/CT — sin reemplazar tu parque instalado.":"Trabalhamos sobre qualquer marca de equipamentos MRI/CT — sem trocar o seu parque instalado.",
 "Tres herramientas de IA que cubren todo el flujo de imágenes":"Três ferramentas de IA que cobrem todo o fluxo de imagem",
 "USA":"EUA",
 "USA — laboratorio de restauración de bobinas, RF y gradientes":"EUA — laboratório de restauração de bobinas, RF e gradientes",
 "Un dispositivo compacto y no invasivo más una plataforma en la nube que monitorean tus equipos 24/7 — sin acceder a datos de pacientes. Relevan el estado técnico de cada resonador (nivel de helio, cold head, presión del magneto, riesgo de quench) y lo combinan con los datos de producción del centro para darte inteligencia operativa, financiera y de personal en MRI y CT.":"Um dispositivo compacto e não invasivo mais uma plataforma na nuvem que monitoram os seus equipamentos 24/7 — sem acessar dados de pacientes. Coletam o estado técnico de cada ressonador (nível de hélio, cold head, pressão do magneto, risco de quench) e o combinam com os dados de produção do centro para oferecer inteligência operacional, financeira e de equipe em MRI e CT.",
 "Un equipo de ingeniería multimarca, tres laboratorios propios. Te respondemos desde la sede más cercana.":"Uma equipe de engenharia multimarca, três laboratórios próprios. Respondemos a partir da unidade mais próxima.",
 "Un equipo multidisciplinario en ingeniería técnica, comercial y administrativa en toda la región.":"Uma equipe multidisciplinar em engenharia técnica, comercial e administrativa em toda a região.",
 "Un visor DICOM de alto rendimiento creado por radiólogos, integrado de forma nativa con IA de dictado por voz. El radiólogo dicta, las mediciones del estudio se inyectan solas y el informe estructurado queda listo en una fracción del tiempo — reduciendo un 70% la redacción y acelerando la entrega de resultados a tus pacientes.":"Um visualizador DICOM de alto desempenho criado por radiologistas, integrado de forma nativa com IA de ditado por voz. O radiologista dita, as medições do estudo são inseridas automaticamente e o laudo estruturado fica pronto em uma fração do tempo — reduzindo 70% a redação e acelerando a entrega de resultados aos seus pacientes.",
 "Un visor de estudios con IA de transcripción integrada para radiólogos informantes. Dictá con naturalidad y dejá que la IA redacte el informe — reduciendo un 70% el tiempo de redacción, aumentando la producción de informes y acortando los tiempos de entrega a tus pacientes.":"Um visualizador de estudos com IA de transcrição integrada para radiologistas laudadores. Dite com naturalidade e deixe a IA redigir o laudo — reduzindo 70% o tempo de redação, aumentando a produção de laudos e encurtando os prazos de entrega aos seus pacientes.",
 "Un único tablero para todas tus sedes y marcas de equipos":"Um único painel para todas as suas unidades e marcas de equipamentos",
 "Una plataforma de monitoreo que releva los datos técnicos de tus equipos y los datos de producción de tu centro en tiempo real — convirtiendo la actividad DICOM en inteligencia operativa, financiera y de personal para MRI y CT.":"Uma plataforma de monitoramento que coleta os dados técnicos dos seus equipamentos e os dados de produção do seu centro em tempo real — transformando a atividade DICOM em inteligência operacional, financeira e de equipe para MRI e CT.",
 "Velo sobre tus propios estudios":"Veja nos seus próprios estudos",
 "Venta de equipos MRI/CT y proyectos llave en mano, más un stock de piezas críticas recuperadas y testeadas — multimarca.":"Venda de equipamentos MRI/CT e projetos turnkey, mais um estoque de peças críticas recuperadas e testadas — multimarca.",
 "Venta y proyectos llave en mano de MRI/CT, más stock de piezas críticas recuperadas y testeadas.":"Venda e projetos turnkey de MRI/CT, mais estoque de peças críticas recuperadas e testadas.",
 "Venta, instalación y proyectos llave en mano, con asesoramiento técnico multimarca.":"Venda, instalação e projetos turnkey, com assessoria técnica multimarca.",
 "Ver catálogo →":"Ver catálogo →",
 "Ver productos":"Ver produtos",
 "Ver productos →":"Ver produtos →",
 "Visibilidad y control sobre tus equipos, tu producción y tus finanzas. Optimizá la distribución de turnos, anticipá la demanda y sacá más capacidad de cada equipo — sin comprar hardware nuevo.":"Visibilidade e controle sobre os seus equipamentos, a sua produção e as suas finanças. Otimize a distribuição de turnos, antecipe a demanda e extraia mais capacidade de cada equipamento — sem comprar hardware novo.",
 "Visor + IA de transcripción":"Visualizador + IA de transcrição",
 "Visor integrado + IA de transcripción en un mismo flujo":"Visualizador integrado + IA de transcrição em um mesmo fluxo",
 "[Jefe técnico]":"[Chefe técnico]",
 "[Nombre del director]":"[Nome do diretor]",
 "[Nombre del médico]":"[Nome do médico]",
 "[Responsable de operaciones]":"[Responsável de operações]",
 "autorizado":"autorizado",
 "años de experiencia":"anos de experiência",
 "clientes en la región":"clientes na região",
 "dosis al paciente en PET-CT":"dose ao paciente em PET-CT",
 "dosis · PET-CT":"dose · PET-CT",
 "más producción de estudios":"mais produção de estudos",
 "parte de Grupo Nexo":"parte do Grupo Nexo",
 "producción":"produção",
 "producción de informes":"produção de laudos",
 "reparaciones realizadas":"reparos realizados",
 "tiempo de entrega":"prazo de entrega",
 "tiempo de entrega de informes":"prazo de entrega de laudos",
 "tiempo de redacción":"tempo de redação",
 "tiempo de redacción de informes":"tempo de redação de laudos",
 "¡Gracias! Tu consulta fue preparada. Te contactaremos a la brevedad.":"Obrigado! Sua consulta foi preparada. Entraremos em contato em breve.",
 "¡Gracias! Tu solicitud fue preparada. Te contactaremos a la brevedad.":"Obrigado! Sua solicitação foi preparada. Entraremos em contato em breve.",
 "© 2026 Nexolibre — parte de <b>Grupo Nexo</b>. Todos los derechos reservados.":"© 2026 Nexolibre — parte do <b>Grupo Nexo</b>. Todos os direitos reservados.",
 "¿Buscás una pieza puntual?":"Procurando uma peça específica?",
 "¿Empezamos?":"Vamos começar?",
 "¿Necesitás soporte o una pieza puntual?":"Precisa de suporte ou de uma peça específica?",
 "¿No encontraste tu pieza?":"Não encontrou a sua peça?",
}

PH = {
 "Buscar pieza, modelo o N° de parte…":"Buscar peça, modelo ou nº de peça…",
 "Centro / clínica / hospital":"Centro / clínica / hospital",
 "Contanos tu necesidad (equipo, modelo, pieza…)":"Conte a sua necessidade (equipamento, modelo, peça…)",
 "Contanos tu necesidad…":"Conte a sua necessidade…",
 "Tu nombre":"Seu nome",
}

def esc(v): return v.replace('"','&quot;')

files = [f for f in glob.glob("*.html") if not f.startswith("Copia")]
covered=set()
for f in files:
    s=open(f,encoding="utf-8").read()
    for es,pt in TR.items():
        pat=re.compile(re.escape('data-es="'+es+'"')+r'(?! data-pt=)')
        s,n=pat.subn('data-es="'+es+'" data-pt="'+esc(pt)+'"', s)
        if n: covered.add(es)
    for es,pt in PH.items():
        pat=re.compile(re.escape('data-es-ph="'+es+'"')+r'(?! data-pt-ph=)')
        s=pat.sub('data-es-ph="'+es+'" data-pt-ph="'+esc(pt)+'"', s)
    open(f,"w",encoding="utf-8").write(s)

# Reportar data-es sin traducción
missing=set()
for f in files:
    s=open(f,encoding="utf-8").read()
    for m in re.findall(r'data-es="([^"]*)"', s):
        if m not in TR: missing.add(m)
print("Traducciones aplicadas (claves cubiertas):", len(covered), "/", len(TR))
print("SIN traducir (faltantes):", len(missing))
for m in sorted(missing): print("  -", m)